%YAML 1.1
---
name: guvcview
title: GTK+ UVC Viewer (UNOFFICIAL)
summary: A simple v4l2 full-featured video grabber
description: >
  GTK+ UVC Viewer is a simple interface for capturing and viewing video from v4l2 devices, with a special emphasis for the linux uvc driver.
    
  This package provides a control interface based on Gtk3  A console only option is also available.
    
  You can also use guvcview has a control window only, (from console: `guvcview.control-panel`), this allows image control on other apps, like ekiga, cheese, mplayer, skype, ...

  OPTIONAL SECURITY CONFINEMENT INTERFACES:

  * Connect the snap to the `removable-media` interface to allow the application to save file under /media and /run/media:
    
    # snap connect guvcview:removable-media

  This package is NOT official, for any problem regarding using the package please refer to:
  
  https://github.com/Lin-Buo-Ren/guvcview-snap/issues

icon: snap/gui/guvcview.png
license: GPL-3.0

adopt-info: guvcview
assumes:
# `full` adapter
- snapd2.36

base: core18
confinement: strict
grade: stable

parts:
  # Files to patch the files in the snap
  patching:
    source: snap/local/patching
    plugin: dump
    organize:
      '*': patching/
    prime:
    - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    stage-packages:
    - v4l-utils
    organize:
      '*-launch': bin/
    stage:
    - -bin/README.*

  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity-integration:
    plugin: nil
    stage-snaps:
    - zenity-integration

  # Speeding up packaging development iteration by using compiler cache
  # https://forum.snapcraft.io/t/the-ccache-build-snap/10820
  #ccache:
    #plugin: nil
    #build-snaps:
    #- ccache
    #prime:
    #- -*

  # Prebuilt upstream FFmpeg for integration
  # https://forum.snapcraft.io/t/the-ffmpeg-sdk-stage-snaps/10818
  ffmpeg-sdk:
    plugin: nil
    stage-snaps:
    - ffmpeg-sdk-gplv3
    stage-packages:
    ### Dynamic-linking safe dependencies
    - libasound2
    - libass9
    - libbluray2
    - libbs2b0
    - libcaca0
    - libdrm2
    - libfontconfig1
    - libfribidi0
    - libgmp10
    - libgraphite2-3
    - libharfbuzz0b
    - libmp3lame0
    - try:
      - libnuma1
    - libogg0
    - libopencore-amrnb0
    - libopencore-amrwb0
    - libopus0
    - libslang2
    - libtheora0
    - libva-drm2
    - libva-x11-2
    - libva2
    - libvdpau1
    - libvo-amrwbenc0
    - libvorbis0a
    - libvorbisenc2
    - libvpx5
    - libx11-6
    - libxau6
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-xfixes0
    - libxdmcp6
    - libxext6
    - libxfixes3

    ### GPL dependencies
    - libcdio-cdda2
    - libcdio-paranoia2
    - libcdio17
    - libfftw3-double3
    - librubberband2
    - libsamplerate0
    - libx264-152
    - libx265-146
    - libxvidcore4

    ### GPLv3 dependencies
    - libsmbclient

    filesets:
      library-shared:
      - '**/lib/**/*.so*'

    prime:
    - $library-shared

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk

    plugin: make
    build-packages:
    - build-essential
    - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  # Scriptlet to check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout
    prime:
    - -*

  guvcview:
    after:
    #- ccache
    - ffmpeg-sdk
    - patching
    - selective-checkout
    source: git://git.code.sf.net/p/guvcview/git-master
    source-depth: 30

    # For stable releases
    #source-tag: v2.0.6

    override-pull: |
      set -o nounset

      snapcraftctl pull
      "${SNAPCRAFT_STAGE}"/scriptlets/selective-checkout \
        --append-packaging-revision

      patch \
        --strip=1 \
        < "${SNAPCRAFT_STAGE}"/patching/guvcview-fix-missing-c-locale-definitions.patch

    plugin: autotools
    configflags:
    # WORKAROUND: 
    # guvcview's resource data path not relocatable, we set prefix to /usr
    # so that the existing /usr/share tree in Ubuntu Core can be used to
    # set up layouts.
    - --prefix=/usr

    # Speed up snap building by using ccache
    #- CC=ccache gcc
    #- CXX=ccache g++

    build-packages:
    # Replaced by `ffmpeg` part
    #- libavcodec-dev
    #- libavutil-dev

    - libasound2

    - autoconf
    - automake
    - intltool
    - libglib2.0-dev
    - libgsl-dev
    - libgtk-3-dev
    - libpng-dev
    - libsdl2-dev
    - libtool
    - libudev-dev
    - libusb-1.0-0-dev
    - libv4l-dev
    - portaudio19-dev

    stage-packages:
    # Accelerated Renderer support for libSDL2
    - libglu1-mesa
    - libgl1-mesa-dri

    - libv4l-0
    - libv4lconvert0
    - libgsl23
    - libportaudio2
    - libpulse0
    - libsdl2-2.0-0
    - libusb-1.0-0

    filesets:
      appdata:
      - usr/share/appdata/*
      desktop-entries:
      - usr/share/applications/*
      documentations:
      - usr/share/doc/*
      executables:
      - usr/bin/*

      # Special case for x11-common package
      # https://bugs.launchpad.net/snapcraft/+bug/1824077
      - -usr/bin/X11

      library-headers:
      - usr/include/*
      localizations:
      - usr/share/locale/*
      manpages:
      - usr/share/man/*
      pixmaps:
      - usr/share/pixmaps/*
      pkgconfig:
      - usr/lib/pkgconfig/*
      shared-libraries:
      - usr/lib/**/*.so*
      - lib/**/*.so*
      static-libraries:
      - usr/lib/*.a
    stage:
    - $executables
    - $desktop-entries
    - $library-headers
    - $localizations
    - $manpages
    - $pkgconfig
    - $pixmaps
    - $shared-libraries
    override-prime: |
      set -o nounset

      snapcraftctl prime

      cp \
        --force \
        --verbose \
        usr/share/applications/guvcview.desktop \
        usr/share/applications/guvcview-control-panel.desktop

      # Fixup desktop entry
      sed \
        --in-place \
        --file "${SNAPCRAFT_STAGE}"/patching/patch-desktop-entries-control-panel.sed \
        usr/share/applications/guvcview-control-panel.desktop
      "${SNAPCRAFT_STAGE}"/patching/patch-desktop-entries.bash

    prime:
    - $executables
    - $desktop-entries
    - $localizations
    - $manpages
    - $pixmaps
    - $shared-libraries

apps:
  guvcview:
    adapter: full
    # WORKAROUND: Snapcraft impose too much restrictions to the command format
    # https://bugs.launchpad.net/snapcraft/+bug/1820055
    command: bin/guvcview-launch
    command-chain:
    - bin/desktop-launch
    desktop: usr/share/applications/guvcview.desktop
    environment:
      # Fix ALSA
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf

  control-panel:
    adapter: full
    # WORKAROUND: Snapcraft impose too much restrictions to the command format
    # https://bugs.launchpad.net/snapcraft/+bug/1820055
    command: bin/guvcview.control_panel-launch
    command-chain:
    - bin/desktop-launch
    desktop: usr/share/applications/guvcview-control-panel.desktop

plugs:
  # Audio access
  alsa:
  pulseaudio:

  # V4L device access
  camera: # Non-A-C

  # Common desktop interfaces
  # https://forum.snapcraft.io/t/the-desktop-interfaces/2042
  desktop:
  desktop-legacy:
  unity7:
  wayland:

  # GNOME and Gtk runtime via content sharing
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804

  # Gtk Common Themes support
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

  # Unknown, related with H264 panel
  hardware-observe:

  # Storage access
  home:
  removable-media: # Non-A-C

  # For SDL2 hardware acceleration
  opengl:

  # Canonical config path access
  # https://forum.snapcraft.io/t/the-personal-files-interface/9357
  # FIXME: Waiting for autoconnection grant on the store
  # https://forum.snapcraft.io/t/interface-auto-connect-request-for-the-guvcview-snap-personal-files/10858
  #user-guvcview-config:
    #interface: personal-files
    #write:
    #- $HOME/.config/guvcview2

  # Recommendations from snappy-debug
  screen-inhibit-control:

layout:
  # Fix resource relocation problem of zenity part
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity

  # Fix missing icon of guvcview
  /usr/share/pixmaps/guvcview:
    symlink: $SNAP/usr/share/pixmaps/guvcview
