%YAML 1.1
---
name: guvcview
version: determined-by-version-script
version-script: |
  set -eu

  upstream_version="$(
    git \
      -C parts/guvcview/src \
      describe \
      --always \
      --dirty=-d \
      --tags \
    | sed s/^v//
  )"

  packaging_revision="$(
    git \
      describe \
      --abbrev=4 \
      --always \
      --dirty=-d
  )"

  printf -- '%s' "${upstream_version}+pkg-${packaging_revision}"

summary: A simple v4l2 full-featured video grabber
description: >
  GTK+ UVC Viewer is a simple interface for capturing and viewing video from v4l2 devices, with a special emphasis for the linux uvc driver.
    
  This package provides a control interface based on Gtk3  A console only option is also available.
    
  You can also use guvcview has a control window only, (from console: `guvcview --control_only`), this allows image control on other apps, like ekiga, cheese, mplayer, skype, ...

  OPTIONAL SECURITY CONFINEMENT INTERFACES:
  
  * Connect the snap to the `hardware-observe` interface if your camera supports H.264 hardware encoding:
  
    # snap connect guvcview-brlin:hardware-observe
  
  * Connect the snap to the `removable-media` interface to allow the application to save file under /media and /run/media:
    
    # snap connect guvcview-brlin:removable-media

  This package is NOT official, for any problem regarding using the package please refer to:
  
  https://github.com/Lin-Buo-Ren/guvcview-snap/issues
confinement: strict
grade: stable
icon: snap/gui/guvcview.png
architectures:
- build-on: i386
- build-on: amd64
- build-on: armhf
- build-on: arm64
- build-on: s390x
#- build-on: ppc64el # FTBFS in alsa part: https://github.com/Lin-Buo-Ren/guvcview-snap/issues/6

plugs:
  # Basic graphical resources
  desktop:

  # Input method framwork/A11Y support
  desktop-legacy:

  # X Window System access
  #x11: # Covered by unity7 interface

  # Unity DE support (e.g. global menu)
  unity7:

  # Wayland support
  wayland:

  # V4L device access
  camera: # Non-A-C

  # Storage access
  home:
  removable-media: # Non-A-C

  # sysfs access
  # Without this access the "H264 controls" page will be missing for H.264 hardware encoding cameras
  hardware-observe: # Non-A-C

  # Audio access
  # `alsa` interface is not necessary
  # https://github.com/diddledan/snapcraft-alsa
  #alsa:
  pulseaudio:

  # For SDL2 hardware acceleration
  opengl:

  # Recommendations from snappy-debug #
  gsettings:
  screen-inhibit-control:

  # According to snapd developers this shouldn't be asserted
  # https://forum.snapcraft.io/t/the-mount-observe-interface/7876/3
  #mount-observe: # Non-A-C

apps:
  guvcview:
    command: >
      desktop-launch
      alsa-launch
      guvcview-launch
      guvcview
      --audio=pulse
    desktop: share/applications/guvcview.desktop

  control-panel:
    command: >
      desktop-launch
      alsa-launch
      guvcview-launch
      guvcview
      --control_panel

parts:
  # Patches to fix other parts
  patches:
    source: snap/local/patches
    plugin: dump

    organize:
      '*': patches/

    prime:
    - -patches/

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  # Optional auxiliary part for displaying simple dialogs for better user experience, powered by Zenity
  # https://forum.snapcraft.io/t/the-zenity-remote-part/8793
  zenity:
    # This part or part recipe is needed until LP#1766878 is fixed
    #
    # Bug #1766878 “$SNAPCRAFT_PROJECT_NAME used in a remote part expands to wrong value” : Bugs : Snapcraft
    # https://bugs.launchpad.net/snapcraft/+bug/1766878
    configflags:
    - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
    - --disable-libnotify
    - --disable-webkitgtk
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /

  # Remote part for speeding up other parts' building
  ccache:

  # Custom built ffmpeg libraries for audio/video encoding
  # DOC: CompilationGuide/Ubuntu – FFmpeg
  #      https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
  # NOTE: Only components that is compatible with GPL can be enabled!
  # FIXME: Other encoding format support requires enabling
  ffmpeg:
    after:
      - ccache

    source: git://github.com/FFmpeg/FFmpeg.git
    source-type: git
    source-tag: release/3.4
    source-depth: 1

    plugin: autotools
    configflags:
      - --enable-gpl
      #- --enable-nonfree

      #- --enable-libfdk-aac
      - --enable-libmp3lame
      - --enable-libopus
      - --enable-libtheora
      - --enable-libvpx
      - --enable-libx264
      # --enable-libx265

      - --enable-shared

      - --disable-doc
      - --disable-programs

      - --prefix=/

    build-packages:
      # Base dependencies
      - autoconf
      - automake
      - build-essential
      - cmake
      - git-core
      - libass-dev
      - libfreetype6-dev
      - libsdl2-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - texinfo
      - wget
      - zlib1g-dev

      # An assembler used by some libraries
      - yasm

      # H.264 video encoder
      - libx264-dev

      # H.265/HEVC video encoder
      #- libx265-dev
      #- libnuma-dev

      # VP8/VP9 video encoder/decoder
      - libvpx-dev

      # AAC audio encoder
      # Incompatible with --enable-gpl
      #- libfdk-aac-dev

      # MP3 audio encoder
      - libmp3lame-dev

      # Opus audio decoder and encoder
      - libopus-dev

      # AV1 video encoder/decoder not provided by Ubuntu 16.04
      #- libaom-av1-dev(?)

      # OGG/Theora video codec
      - libtheora-dev

    stage-packages:
      - libasyncns0
      - libdb5.3
      - libflac8
      - libjack-jackd2-0
      - libmp3lame0
      - libogg0
      - libopus0
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libsndio6.1
      - libtheora0
      - libva-drm1
      - libva-x11-1
      - libva1
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvpx3
      - libxcb-shape0
      - libxcb-shm0
      - libxss1
      - libxv1
      - libxxf86vm1
      - libx264-148

    filesets:
      examples:
        - share/ffmpeg/examples/*
      executables:
        - bin/*
      files-in-staged-packages:
        # Avoid staging usr/local
        - usr/bin
        - usr/include
        - usr/lib
        - usr/share
        - -usr/share/alsa/*
      library-headers:
        - include/*
      manpages:
        - share/man/*
      pkg-config:
        - lib/pkgconfig/*
      shared-libraries:
        - lib/*.so*
      static-libraries:
        - lib/*.a
    stage:
      - $files-in-staged-packages
      - $library-headers
      - $pkg-config
      - $shared-libraries
      - $static-libraries
    override-stage: |
      set -eu

      snapcraftctl stage

      # PATCH: ffmpeg's libdir and includedir isn't
      #        depend on ${prefix}
      sed \
        --in-place \
        's#dir=/#dir=${prefix}#' \
        "${SNAPCRAFT_STAGE}"/lib/pkgconfig/*.pc
    prime:
      - $files-in-staged-packages
      - $shared-libraries

  # ALSA part for snapcraft, which will compile ALSA and install a
  # loader script which redirects audio through pulseaudio without
  # requiring the `alsa` plug to be connected manually or by store
  # assertion.
  # https://github.com/diddledan/snapcraft-alsa
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-lib:
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    #- --disable-rawmidi # required by ffmpeg part
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
  alsa-plugins:
    after: [alsa-lib]
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-arcamav
    - --disable-avcodec
    - --disable-jack
    - --disable-mix
    - --disable-oss
    - --disable-usbstream
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib

  desktop-gtk3:

  guvcview:
    after:
      - ccache
      - ffmpeg
      - patches
    source: git://git.code.sf.net/p/guvcview/git-master
    source-depth: 30

    # For stable releases
    #source-tag: v2.0.6

    override-pull: |
      set -eu

      snapcraftctl pull

      patch \
        --strip=1 \
        < "${SNAPCRAFT_STAGE}"/patches/guvcview-fix-missing-c-locale-definitions.patch

    plugin: autotools
    configflags:
      # WORKAROUND: Resource data path not relocatable
      - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current

    build-packages:
      # Ubuntu 16.04 provided FFmpeg is too old
      # Replaced by `ffmpeg` remote part
      #- libavcodec-dev
      #- libavutil-dev

      # DISABLED: Requires manual patching, replaced by alsa-lib part
      # https://forum.snapcraft.io/t/reusable-alsa-lib-part/3556
      #- libasound2

      - autoconf
      - automake
      - intltool
      - libglib2.0-dev
      - libgsl-dev
      - libgtk-3-dev
      - libpng12-dev
      - libsdl2-dev
      - libtool
      - libudev-dev
      - libusb-1.0-0-dev
      - libv4l-dev
      - portaudio19-dev

    stage-packages:
      # Accelerated Renderer support for libSDL2
      - libglu1-mesa
      - libgl1-mesa-dri

      - libv4l-0
      - libv4lconvert0
      - libgsl2
      - libportaudio2
      - libpulse0
      - libusb-1.0-0
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/: /
    filesets:
      appdata:
        - share/appdata/*
      desktop-entries:
        - share/applications/*
      documentations:
        - share/doc/*
      executables:
        - bin/*
      files-from-stage-packages:
        - usr/*

        # Special case for libusb-1.0.so.0
        - lib/x86_64-linux-gnu/*

        # Exclude ALSA files which conflicts with alsa part
        - -usr/share/alsa/*
      library-headers:
        - include/*
      localizations:
        - share/locale/*
      manpages:
        - share/man/*
      pixmaps:
        - share/pixmaps/*
      pkgconfig:
        - lib/pkgconfig/*
      shared-libraries:
        - lib/*.so*
      static-libraries:
        - lib/*.a
    stage:
      - $executables
      - $desktop-entries
      - $files-from-stage-packages
      - $library-headers
      - $localizations
      - $manpages
      - $pkgconfig
      - $pixmaps
      - $shared-libraries
    override-stage: |
      set -eu

      snapcraftctl stage

      # Fixup desktop entry
      sed \
        --in-place \
        --file "${SNAPCRAFT_STAGE}"/patches/postprocess-desktop-entries.sed \
        "${SNAPCRAFT_STAGE}"/share/applications/guvcview.desktop
    prime:
      - $executables
      - $desktop-entries
      - $files-from-stage-packages
      - $localizations
      - $manpages
      - $pixmaps
      - $shared-libraries
