name: guvcview
version: git
summary: A simple v4l2 full-featured video grabber
description: >
  GTK+ UVC Viewer is a simple interface for capturing and viewing video from v4l2 devices, with a special emphasis for the linux uvc driver.

  This package provides a control interface based on Gtk3  A console only option is also available.

  You can also use guvcview has a control window only, (from console: guvcview --control_only), this allows image control on other apps, like ekiga, cheese, mplayer, skype, ...
confinement: devmode
grade: devel
